/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Menus;

import Archivos.GuardadoArchivos;
import Archivos.GuardadoHistorialUsuario;
import Archivos.GuardadoRanking;
import Excepciones.ListaException;
import Listas.ListaGenerica;
import Logins.Frontent.VentanaEleccionUsuario;
import OpcionesAdministrador.Estadisticas.ColocarEstadisticasHistorial;
import OpcionesAdministrador.Estadisticas.ColocarEstadisticasRanking;
import OpcionesSucursalProducto.ColocarPlantillas;
import OpcionesSucursalProducto.Frontent.VentanaCrearProducto;
import OpcionesSucursalProducto.Frontent.VentanaHabilitarProductos;
import OpcionesSucursalProducto.Frontent.VentanaEstadisticas;
import SQL.Productos.Producto;
import Usuario.Usuario;
import java.sql.SQLException;
import javax.swing.JOptionPane;


/**
 *
 * @author millin-115
 */
public class VentanaMenuAdministrador extends javax.swing.JFrame {
    
    private VentanaEleccionUsuario inicioSesion;
    private final VentanaHabilitarProductos ventanaProductos;
    private final ColocarPlantillas colocarPlantillas;
    private final VentanaCrearProducto ventanaCrearProducto;
    private VentanaEstadisticas ventanaEstadisticas;
    private ColocarEstadisticasRanking colocarEstadisticas;
    private GuardadoArchivos guardadoArchivosRanking;
    private ColocarEstadisticasHistorial colocarEstadisticasHistorial;
    private GuardadoArchivos guardadoHistorialUsuario;
    private ListaGenerica<Producto> productosDeSucursal;
    private Usuario usuario;
    
    public VentanaMenuAdministrador(VentanaHabilitarProductos ventanaProductos, ColocarPlantillas colocarPlantillas, VentanaCrearProducto ventanaCrear) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.ventanaProductos = ventanaProductos;
        this.colocarPlantillas = colocarPlantillas;
        this.ventanaCrearProducto = ventanaCrear;
    }
    
    public void setEleccionUsuario(VentanaEleccionUsuario inicioSesion) {
        this.inicioSesion = inicioSesion;
    }

    public void setOpcionesEstadisticas(VentanaEstadisticas ventanaRanking) {
        this.ventanaEstadisticas = ventanaRanking;
        this.colocarEstadisticas = new ColocarEstadisticasRanking(ventanaRanking);
        this.guardadoArchivosRanking = new GuardadoRanking(colocarEstadisticas);
        
        this.colocarEstadisticasHistorial = new ColocarEstadisticasHistorial(ventanaRanking);
        this.guardadoHistorialUsuario = new GuardadoHistorialUsuario(colocarEstadisticasHistorial);
    }

    public void setProductosDeSucursal(ListaGenerica<Producto> productosDeSucursal) {
        this.productosDeSucursal = productosDeSucursal;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
        colocarPlantillas.setUsuario(usuario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonGestionarProductos = new javax.swing.JButton();
        botonEstadisticas = new javax.swing.JButton();
        botonRanking = new javax.swing.JButton();
        botonRegresar = new javax.swing.JButton();
        botonGestionarProductos1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonGestionarProductos.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        botonGestionarProductos.setText("Gestionar Productos");
        botonGestionarProductos.addActionListener(this::botonGestionarProductosActionPerformed);

        botonEstadisticas.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        botonEstadisticas.setText("Ver Historial de Usuarios");
        botonEstadisticas.addActionListener(this::botonEstadisticasActionPerformed);

        botonRanking.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        botonRanking.setText("Ver Ranking");
        botonRanking.addActionListener(this::botonRankingActionPerformed);

        botonRegresar.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        botonRegresar.setText("Regresar");
        botonRegresar.addActionListener(this::botonRegresarActionPerformed);

        botonGestionarProductos1.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        botonGestionarProductos1.setText("Crear Productos");
        botonGestionarProductos1.addActionListener(this::botonGestionarProductos1ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonRegresar)
                .addGap(20, 20, 20))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(botonGestionarProductos1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(botonGestionarProductos))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(botonRanking))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(botonEstadisticas)))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(botonRegresar)
                .addGap(33, 33, 33)
                .addComponent(botonGestionarProductos1)
                .addGap(18, 18, 18)
                .addComponent(botonGestionarProductos)
                .addGap(18, 18, 18)
                .addComponent(botonRanking)
                .addGap(18, 18, 18)
                .addComponent(botonEstadisticas)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonGestionarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGestionarProductosActionPerformed
        try {
            colocarPlantillas.colocar(productosDeSucursal, usuario.getNombreSucursal());
            this.setVisible(false);
            ventanaProductos.setVisible(true);
        } catch (ListaException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_botonGestionarProductosActionPerformed

    private void botonEstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEstadisticasActionPerformed
        try {
            colocarEstadisticasHistorial.colocarEstadisticasSucursal(usuario);
            this.setVisible(false);
            ventanaEstadisticas.setTituloEstadisticas("Historiales Globales");
            ventanaEstadisticas.setGuardadoEstadistica(guardadoHistorialUsuario);
            ventanaEstadisticas.setVentanaAnterior(this);
            ventanaEstadisticas.setVisible(true);
        } catch (SQLException | ClassNotFoundException | ListaException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_botonEstadisticasActionPerformed

    private void botonRankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRankingActionPerformed
        try {
            colocarEstadisticas.colocarEstadisticasPorSucursal(usuario);
            this.setVisible(false);
            ventanaEstadisticas.setTituloEstadisticas("Ranking de la sucursal "+usuario.getNombreSucursal());
            ventanaEstadisticas.setGuardadoEstadistica(guardadoArchivosRanking);
            ventanaEstadisticas.setVentanaAnterior(this);
            ventanaEstadisticas.setVisible(true);
        } catch (SQLException | ClassNotFoundException | ListaException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_botonRankingActionPerformed

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
        this.setVisible(false);
        inicioSesion.setVisible(true);
    }//GEN-LAST:event_botonRegresarActionPerformed

    private void botonGestionarProductos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGestionarProductos1ActionPerformed
        this.setVisible(false);
        ventanaCrearProducto.setVisible(true);
        ventanaCrearProducto.setVentanaAnterior(this);
    }//GEN-LAST:event_botonGestionarProductos1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEstadisticas;
    private javax.swing.JButton botonGestionarProductos;
    private javax.swing.JButton botonGestionarProductos1;
    private javax.swing.JButton botonRanking;
    private javax.swing.JButton botonRegresar;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
    public void mostrar() {
        this.setVisible(true);
    }
    
}
