/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Menus;

import Archivos.GuardadoArchivos;
import Archivos.GuardadoHistorialUsuario;
import Archivos.GuardadoRanking;
import ControlCocina.OrganizadorDeCocina;
import Excepciones.ListaException;
import Excepciones.PartidaException;
import FrontentCocina.VentanaPizzaExpressTycoon;
import Logins.Frontent.VentanaEleccionUsuario;
import OpcionesAdministrador.Estadisticas.ColocarEstadisticasRanking;
import OpcionesAdministrador.Estadisticas.ColocarEstadisticasHistorial;
import OpcionesSucursalProducto.Frontent.VentanaCrearProducto;
import OpcionesSucursalProducto.Frontent.VentanaEstadisticas;
import OpcionesSuperAdmin.Frontent.VentanaCambiarUsuario;
import OpcionesSuperAdmin.Frontent.VentanaCrearSucursal;
import OpcionesSuperAdmin.Frontent.VentanaCrearUsuario;
import OpcionesSuperAdmin.Sucursal.ColocarPlantillasSuperAdmin;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author millin-115
 */
public class VentanaMenuSuperAdmin extends javax.swing.JFrame {
    
    private VentanaEleccionUsuario eleccionUsuario;
    private VentanaCrearSucursal crearSucursal;
    private VentanaCrearUsuario crearUsuario;
    private ColocarPlantillasSuperAdmin plantillasSuperAdmin;
    private final VentanaCrearProducto crearProducto;
    private VentanaCambiarUsuario ventanaCambiarUsuario;
    private VentanaEstadisticas ventanaEstadisticas;
    private ColocarEstadisticasRanking colocarEstadisticas;
    private GuardadoArchivos guardadoArchivosRanking;
    private ColocarEstadisticasHistorial colocarEstadisticasHistorial;
    private GuardadoArchivos guardadoHistorialUsuario;
    private final OrganizadorDeCocina organizadorCocina;
    private final VentanaPizzaExpressTycoon ventanaCocina;
    
    public VentanaMenuSuperAdmin(VentanaCrearProducto ventanaCrearProducto, OrganizadorDeCocina organizadorCocina) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.crearProducto = ventanaCrearProducto;
        this.organizadorCocina = organizadorCocina;
        this.ventanaCocina = organizadorCocina.getVentanaCocina();
    }
    
    public void setEleccionUsuario(VentanaEleccionUsuario eleccionUsuario) {
        this.eleccionUsuario = eleccionUsuario;
    }
    
    public void setCrearSucursal(VentanaCrearSucursal crearSucursal) {
        this.crearSucursal = crearSucursal;
    }
    
    public void setOpcionesCrearUsuario(VentanaCrearUsuario crearUsuario, ColocarPlantillasSuperAdmin plantillasSuperAdmin) {
        this.crearUsuario = crearUsuario;
        this.plantillasSuperAdmin = plantillasSuperAdmin;
    }

    public void setVentanaCambiarUsuario(VentanaCambiarUsuario ventanaCambiarUsuario) {
        this.ventanaCambiarUsuario = ventanaCambiarUsuario;
    }
    
    public void setOpcionesRanking(VentanaEstadisticas ventanaRanking) {
        this.ventanaEstadisticas = ventanaRanking;
        this.colocarEstadisticas = new ColocarEstadisticasRanking(ventanaRanking);
        this.guardadoArchivosRanking = new GuardadoRanking(colocarEstadisticas);
        
        this.colocarEstadisticasHistorial = new ColocarEstadisticasHistorial(ventanaRanking);
        this.guardadoHistorialUsuario = new GuardadoHistorialUsuario(colocarEstadisticasHistorial);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonJugar = new javax.swing.JButton();
        botonHistorial = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        botonCrearSucursal = new javax.swing.JButton();
        botonCrearUsuario = new javax.swing.JButton();
        botonCrearProducto = new javax.swing.JButton();
        botonCambiarSucursalUsuario = new javax.swing.JButton();
        botonRanking = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonJugar.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        botonJugar.setText("Jugar a Pizza Express Tycoon");
        botonJugar.addActionListener(this::botonJugarActionPerformed);

        botonHistorial.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        botonHistorial.setText("Historial de Usuarios");
        botonHistorial.addActionListener(this::botonHistorialActionPerformed);

        jButton1.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        jButton1.setText("Regresar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        botonCrearSucursal.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        botonCrearSucursal.setText("Crear Sucursal");
        botonCrearSucursal.addActionListener(this::botonCrearSucursalActionPerformed);

        botonCrearUsuario.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        botonCrearUsuario.setText("Crear Usuario");
        botonCrearUsuario.addActionListener(this::botonCrearUsuarioActionPerformed);

        botonCrearProducto.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        botonCrearProducto.setText("Crear Producto");
        botonCrearProducto.addActionListener(this::botonCrearProductoActionPerformed);

        botonCambiarSucursalUsuario.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        botonCambiarSucursalUsuario.setText("Cambiar a un Usuario de Sucursal");
        botonCambiarSucursalUsuario.addActionListener(this::botonCambiarSucursalUsuarioActionPerformed);

        botonRanking.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        botonRanking.setText("Ver Ranking Global");
        botonRanking.addActionListener(this::botonRankingActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonHistorial)
                    .addComponent(botonRanking, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonCrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonCrearSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonCrearProducto)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(botonCambiarSucursalUsuario))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(botonJugar)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jButton1)
                .addGap(16, 16, 16)
                .addComponent(botonCrearSucursal)
                .addGap(18, 18, 18)
                .addComponent(botonCrearUsuario)
                .addGap(18, 18, 18)
                .addComponent(botonCrearProducto)
                .addGap(18, 18, 18)
                .addComponent(botonCambiarSucursalUsuario)
                .addGap(18, 18, 18)
                .addComponent(botonRanking)
                .addGap(18, 18, 18)
                .addComponent(botonHistorial)
                .addGap(18, 18, 18)
                .addComponent(botonJugar)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        eleccionUsuario.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botonCrearSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearSucursalActionPerformed
        this.setVisible(false);
        crearSucursal.setVisible(true);
    }//GEN-LAST:event_botonCrearSucursalActionPerformed

    private void botonCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearUsuarioActionPerformed
        try {
            plantillasSuperAdmin.agregarSucursalesParaCrear(crearUsuario);
            this.setVisible(false);
            crearUsuario.setVisible(true);
        } catch (SQLException | ClassNotFoundException | ListaException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_botonCrearUsuarioActionPerformed

    private void botonCrearProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearProductoActionPerformed
        this.setVisible(false);
        crearProducto.setVisible(true);
        crearProducto.setVentanaAnterior(this);
    }//GEN-LAST:event_botonCrearProductoActionPerformed

    private void botonCambiarSucursalUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCambiarSucursalUsuarioActionPerformed
        try {
            plantillasSuperAdmin.agregarOpcionesCambiarSucursal(ventanaCambiarUsuario);
            this.setVisible(false);
            ventanaCambiarUsuario.setVisible(true);
        } catch (SQLException | ClassNotFoundException | ListaException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_botonCambiarSucursalUsuarioActionPerformed

    private void botonRankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRankingActionPerformed
        try {
            colocarEstadisticas.colocarEstadisticasGlobales();
            this.setVisible(false);
            ventanaEstadisticas.setTituloEstadisticas("Ranking Global");
            ventanaEstadisticas.setGuardadoEstadistica(guardadoArchivosRanking);
            ventanaEstadisticas.setVentanaAnterior(this);
            ventanaEstadisticas.setVisible(true);
        } catch (SQLException | ClassNotFoundException | ListaException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_botonRankingActionPerformed

    private void botonHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonHistorialActionPerformed
        try {
            colocarEstadisticasHistorial.colocarEstadisticaGlobal();
            this.setVisible(false);
            ventanaEstadisticas.setTituloEstadisticas("Historiales Globales");
            ventanaEstadisticas.setGuardadoEstadistica(guardadoHistorialUsuario);
            ventanaEstadisticas.setVentanaAnterior(this);
            ventanaEstadisticas.setVisible(true);
        } catch (SQLException | ClassNotFoundException | ListaException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_botonHistorialActionPerformed

    private void botonJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonJugarActionPerformed
        try {
            organizadorCocina.inicializarPartida();
            ventanaCocina.setVentanaAnterior(this);
            this.setVisible(false);
        } catch (SQLException | ClassNotFoundException | PartidaException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_botonJugarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCambiarSucursalUsuario;
    private javax.swing.JButton botonCrearProducto;
    private javax.swing.JButton botonCrearSucursal;
    private javax.swing.JButton botonCrearUsuario;
    private javax.swing.JButton botonHistorial;
    private javax.swing.JButton botonJugar;
    private javax.swing.JButton botonRanking;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
    public void mostrar(boolean mostrar) {
        this.setVisible(mostrar);
    }
    
}
