/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Logins.Frontent;

import com.mycompany.practica1_ipc2_ps.Roles;

/**
 *
 * @author millin-115
 */
public class VentanaEleccionUsuario extends javax.swing.JFrame {
    
    private final VentanaIngresoUsuario ingreso;
    private final Roles roles;
    
    public VentanaEleccionUsuario(VentanaIngresoUsuario ingreso) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.roles = new Roles();
        this.ingreso = ingreso;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botonSuperAdmin = new javax.swing.JButton();
        botonAdmin = new javax.swing.JButton();
        botonJugador = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        jLabel1.setText("Elije el tipo de Usuario");

        botonSuperAdmin.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        botonSuperAdmin.setText("Super Administrador");
        botonSuperAdmin.addActionListener(this::botonSuperAdminActionPerformed);

        botonAdmin.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        botonAdmin.setText("Administrador");
        botonAdmin.addActionListener(this::botonAdminActionPerformed);

        botonJugador.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        botonJugador.setText("Jugador");
        botonJugador.addActionListener(this::botonJugadorActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonSuperAdmin)
                            .addComponent(jLabel1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(botonAdmin))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(botonJugador)))
                .addContainerGap(161, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addComponent(botonSuperAdmin)
                .addGap(50, 50, 50)
                .addComponent(botonAdmin)
                .addGap(48, 48, 48)
                .addComponent(botonJugador)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSuperAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSuperAdminActionPerformed
        ingreso.setTipoRol(roles.superAdmin);
        cambiarVentana();
    }//GEN-LAST:event_botonSuperAdminActionPerformed

    private void botonAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAdminActionPerformed
        ingreso.setTipoRol(roles.admin);
        cambiarVentana();
    }//GEN-LAST:event_botonAdminActionPerformed

    private void botonJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonJugadorActionPerformed
        ingreso.setTipoRol(roles.usuario);
        cambiarVentana();
    }//GEN-LAST:event_botonJugadorActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAdmin;
    private javax.swing.JButton botonJugador;
    private javax.swing.JButton botonSuperAdmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
    private void cambiarVentana() {
        this.setVisible(false);
        ingreso.setVisible(true);
    }
    
}
