/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrontentCocina;

import ControlCocina.ControladorPartida;
import Excepciones.PedidosException;
import Hilos.TiempoPartida;
import java.sql.SQLException;
import javax.swing.JFrame;

/**
 *
 * @author millin-115
 */
public class VentanaPizzaExpressTycoon extends javax.swing.JFrame {
    
    private JFrame ventanaAnterior;
    private ControladorPartida control;
    private TiempoPartida tiempo;
    private boolean partidaActiva;
    
    public VentanaPizzaExpressTycoon() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public void setVentanaAnterior(JFrame ventana) {
        this.ventanaAnterior = ventana;
    }
    
    public void setControlVentana(ControladorPartida control) {
        this.control = control;
    }
    
    public void setTiempo(TiempoPartida tiempo) {
        this.tiempo = tiempo;
    }
    
    public void setPartidaActiva(boolean partidaActiva) {
        this.partidaActiva = partidaActiva;
    }
    
    public boolean getPartidaActiva() {
        return partidaActiva;
    }
    
    public void setEstadoPanel(String estado) {
        textoEstado.setText(estado);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        espacioCocina = new javax.swing.JPanel();
        espacioTiempoPartida = new javax.swing.JLabel();
        estadoPedido = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        espacioPedidos = new javax.swing.JPanel();
        botonAvanzarEstado = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        espacioPedidoAceptado = new javax.swing.JPanel();
        textoEstado = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        espacioConcluidos = new javax.swing.JPanel();
        espacioPuntuacion = new javax.swing.JLabel();
        espacioTiempoPartida2 = new javax.swing.JLabel();
        espacioDatosFinales = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        espacioFinal2 = new javax.swing.JLabel();
        espacioContadorNoentregados = new javax.swing.JLabel();
        espacioContadorCompletados = new javax.swing.JLabel();
        espacioContadorRechazados = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        espacioCocina.setPreferredSize(new java.awt.Dimension(1100, 670));

        espacioTiempoPartida.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        espacioTiempoPartida.setText("Tiempo de Partida 00m: 00s");

        estadoPedido.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        estadoPedido.setText("Pedido Aceptado");

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        jLabel3.setText("Pedidos en Cola");

        espacioPedidos.setLayout(new java.awt.GridLayout(5, 1));
        jScrollPane2.setViewportView(espacioPedidos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                .addContainerGap())
        );

        botonAvanzarEstado.addActionListener(this::botonAvanzarEstadoActionPerformed);

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        jLabel4.setText("Avanza el estado");

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        jLabel5.setText("Presionando el Boton");

        espacioPedidoAceptado.setLayout(new java.awt.BorderLayout());

        textoEstado.setFont(new java.awt.Font("Liberation Sans", 0, 30)); // NOI18N
        textoEstado.setText("Estado");

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        jLabel6.setText("Pedidos Concluidos");

        espacioConcluidos.setLayout(new java.awt.GridLayout(0, 1));
        jScrollPane3.setViewportView(espacioConcluidos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addContainerGap(256, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                .addContainerGap())
        );

        espacioPuntuacion.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        espacioPuntuacion.setText("Puntuacion: 0");

        espacioTiempoPartida2.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        espacioTiempoPartida2.setText("Pizza Express Tycoon");

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        jLabel2.setText("El juego ha terminado y se han conseguido");

        espacioFinal2.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        espacioFinal2.setText("0 puntos");

        espacioContadorNoentregados.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        espacioContadorNoentregados.setText("0 puntos");

        espacioContadorCompletados.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        espacioContadorCompletados.setText("completados");

        espacioContadorRechazados.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        espacioContadorRechazados.setText("rechazados");

        javax.swing.GroupLayout espacioDatosFinalesLayout = new javax.swing.GroupLayout(espacioDatosFinales);
        espacioDatosFinales.setLayout(espacioDatosFinalesLayout);
        espacioDatosFinalesLayout.setHorizontalGroup(
            espacioDatosFinalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(espacioDatosFinalesLayout.createSequentialGroup()
                .addGroup(espacioDatosFinalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(espacioFinal2)
                    .addComponent(espacioContadorCompletados)
                    .addComponent(espacioContadorNoentregados)
                    .addComponent(espacioContadorRechazados))
                .addGap(0, 67, Short.MAX_VALUE))
        );
        espacioDatosFinalesLayout.setVerticalGroup(
            espacioDatosFinalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(espacioDatosFinalesLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(espacioFinal2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(espacioContadorCompletados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(espacioContadorRechazados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(espacioContadorNoentregados)
                .addContainerGap())
        );

        jButton1.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        jButton1.setText("Volver al Menu");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout espacioCocinaLayout = new javax.swing.GroupLayout(espacioCocina);
        espacioCocina.setLayout(espacioCocinaLayout);
        espacioCocinaLayout.setHorizontalGroup(
            espacioCocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(espacioCocinaLayout.createSequentialGroup()
                .addGroup(espacioCocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(espacioCocinaLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(espacioCocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(estadoPedido)
                            .addComponent(espacioPedidoAceptado, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(espacioCocinaLayout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(botonAvanzarEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(97, 97, 97)
                                .addComponent(textoEstado))
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(espacioDatosFinales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(espacioCocinaLayout.createSequentialGroup()
                                .addComponent(espacioTiempoPartida)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(espacioPuntuacion))))
                    .addGroup(espacioCocinaLayout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(espacioCocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(57, 57, 57))
            .addGroup(espacioCocinaLayout.createSequentialGroup()
                .addGap(406, 406, 406)
                .addComponent(espacioTiempoPartida2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        espacioCocinaLayout.setVerticalGroup(
            espacioCocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(espacioCocinaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(espacioTiempoPartida2)
                .addGap(29, 29, 29)
                .addGroup(espacioCocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(espacioCocinaLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(espacioCocinaLayout.createSequentialGroup()
                        .addGroup(espacioCocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(espacioCocinaLayout.createSequentialGroup()
                                .addGroup(espacioCocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(espacioTiempoPartida)
                                    .addComponent(espacioPuntuacion))
                                .addGap(30, 30, 30)
                                .addComponent(estadoPedido)
                                .addGap(18, 18, 18)
                                .addComponent(espacioPedidoAceptado, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(botonAvanzarEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, espacioCocinaLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(textoEstado)
                                .addGap(25, 25, 25)))
                        .addGap(18, 18, 18)
                        .addComponent(espacioDatosFinales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(417, 417, 417))))
        );

        jScrollPane1.setViewportView(espacioCocina);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1115, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 737, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAvanzarEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAvanzarEstadoActionPerformed
        try {
            control.cambiarEstado();
        } catch (PedidosException | SQLException | ClassNotFoundException e) {
            System.out.println("Error... "+e.getMessage());
        }
    }//GEN-LAST:event_botonAvanzarEstadoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        tiempo.interrupt();
        terminarPartida();
        this.setVisible(partidaActiva);
        ventanaAnterior.setVisible(!partidaActiva);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAvanzarEstado;
    private javax.swing.JPanel espacioCocina;
    private javax.swing.JPanel espacioConcluidos;
    private javax.swing.JLabel espacioContadorCompletados;
    private javax.swing.JLabel espacioContadorNoentregados;
    private javax.swing.JLabel espacioContadorRechazados;
    private javax.swing.JPanel espacioDatosFinales;
    private javax.swing.JLabel espacioFinal2;
    private javax.swing.JPanel espacioPedidoAceptado;
    private javax.swing.JPanel espacioPedidos;
    private javax.swing.JLabel espacioPuntuacion;
    private javax.swing.JLabel espacioTiempoPartida;
    private javax.swing.JLabel espacioTiempoPartida2;
    private javax.swing.JLabel estadoPedido;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel textoEstado;
    // End of variables declaration//GEN-END:variables
    
    public void setPuntos(int puntos) {
        espacioPuntuacion.setText("Puntuacion: "+puntos);
        espacioFinal2.setText(puntos+" puntos");
    }
    
    public void actualizarTiempo(int minutos, int segundos) {
        espacioTiempoPartida.setText("Tiempo de Partida "+minutos+"m : "+segundos+"s");
    }
    
    public void comenzarPartida() {
        limpiarConcluidos();
        setPuntos(0);
        partidaActiva = true;
        this.setVisible(true);
        mostrarResultados();
    }
    
    public void terminarPartida() {
        partidaActiva = false;
        mostrarResultados();
    }
    
    public void mostrarResultados() {
        espacioContadorCompletados.setText("Pedidos Completados : "+control.getContadorCompletados());
        espacioContadorRechazados.setText("Pedidos Rechazados : "+control.getContadorRechazados());
        espacioContadorNoentregados.setText("Pedidos No Entregados : "+control.getContadorNoEntregados());
        botonAvanzarEstado.setEnabled(partidaActiva);
        espacioDatosFinales.setVisible(!partidaActiva);
    }
    
    public void escirbirNoEntregados(int noEntregados) {
        espacioContadorNoentregados.setText("Pedidos No Entregados : "+noEntregados);
    }
    
    public void agregarPedido(PlantillaLista plantillaPedido) {
        espacioPedidos.add(plantillaPedido);
        actualizarEspacioPedidos();
    }
    
    public void cambiarAAceptado(PlantillaLista plantillaPedido) {
        espacioPedidoAceptado.add(plantillaPedido);
        actualizarEspacioPedidos();
        actualizarEspacioAceptado();
    }
    
    public void agregarConcluido(PlantillaLista plantillaPedido) {
        espacioConcluidos.add(plantillaPedido);
        actualizarEspacioPedidos();
        actualizarEspacioAceptado();
        actualizarEspacioConcluidos();
    }
    
    private void limpiarConcluidos() {
        espacioPedidoAceptado.removeAll();
        actualizarEspacioAceptado();
        espacioConcluidos.removeAll();
        actualizarEspacioConcluidos();
    }
    
    private void actualizarEspacioPedidos() {
        espacioPedidos.revalidate();
        espacioPedidos.repaint();
    }
    
    private void actualizarEspacioAceptado() {
        espacioPedidoAceptado.revalidate();
        espacioPedidoAceptado.repaint();
    }
    
    private void actualizarEspacioConcluidos() {
        espacioConcluidos.revalidate();
        espacioConcluidos.repaint();
    }
    
}
