/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package OpcionesSuperAdmin.Frontent;

import SQL.Sucursal.Sucursal;
import javax.swing.JOptionPane;

/**
 *
 * @author millin-115
 */
public class PlantillaSucursal extends javax.swing.JPanel {
    
    private final VentanaCrearUsuario ventana;
    private final Sucursal sucursal;
    private boolean elegido;
    
    public PlantillaSucursal(VentanaCrearUsuario ventana, Sucursal sucursal) {
        initComponents();
        this.ventana = ventana;
        this.sucursal = sucursal;
        setTitulo(sucursal.getNombre());
        plantillaElegida(elegido);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        espacioNombre = new javax.swing.JLabel();
        botonElegir = new javax.swing.JButton();
        botonQuitar = new javax.swing.JButton();

        espacioNombre.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        espacioNombre.setText("Sucursal");

        botonElegir.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        botonElegir.setText("Elegir");
        botonElegir.addActionListener(this::botonElegirActionPerformed);

        botonQuitar.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        botonQuitar.setText("Quitar");
        botonQuitar.addActionListener(this::botonQuitarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(espacioNombre)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonElegir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonQuitar)))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(espacioNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonElegir)
                    .addComponent(botonQuitar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonElegirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonElegirActionPerformed
        if (ventana.getSucursal() != null) {
            JOptionPane.showMessageDialog(null, "No se puede elegir mas de una sucursal");
            return;
        }
        ventana.setSucursal(this, sucursal);
        ventana.agregarSucursalElegida();
        plantillaElegida(true);
    }//GEN-LAST:event_botonElegirActionPerformed

    private void botonQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonQuitarActionPerformed
        ventana.quitarEleccion();
        plantillaElegida(false);
    }//GEN-LAST:event_botonQuitarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonElegir;
    private javax.swing.JButton botonQuitar;
    private javax.swing.JLabel espacioNombre;
    // End of variables declaration//GEN-END:variables
    
    private void setTitulo(String titulo) {
        espacioNombre.setText(titulo);
    }
    private void plantillaElegida(boolean elegida) {
        botonQuitar.setVisible(elegida);
        botonElegir.setVisible(!elegida);
    }
}
