/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package OpcionesSuperAdmin.Frontent;

import Menus.VentanaMenuSuperAdmin;
import SQL.Sucursal.Sucursal;
import SQL.Usuario.GestorUsuario;
import Usuario.Usuario;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author millin-115
 */
public class VentanaCambiarUsuario extends javax.swing.JFrame {
    
    private final VentanaMenuSuperAdmin menuSuperAdmin;
    private final GestorUsuario gestorUsuario;
    private PlantillaUsuarioCambio plantilllaUsuario;
    private Usuario usuario;
    private PlantillaSucursalCambio plantillaSucursal;
    private Sucursal sucursal;
    
    public VentanaCambiarUsuario(VentanaMenuSuperAdmin menuSuperAdmin, GestorUsuario gestorUsuario) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.menuSuperAdmin = menuSuperAdmin;
        this.gestorUsuario = gestorUsuario;
    }

    public Usuario getUsuario() {
        return usuario;
    }

    public void setUsuario(PlantillaUsuarioCambio plantilllaUsuario, Usuario usuario) {
        this.plantilllaUsuario = plantilllaUsuario;
        this.usuario = usuario;
    }

    public Sucursal getSucursal() {
        return sucursal;
    }

    public void setSucursal(PlantillaSucursalCambio plantillaSucursal, Sucursal sucursal) {
        this.plantillaSucursal = plantillaSucursal;
        this.sucursal = sucursal;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        espacioUsuarioElegido = new javax.swing.JPanel();
        espacioSucursalElegida = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        espacioUsuarios = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        espacioSucursales = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton2.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        jButton2.setText("Regresar");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        jLabel1.setText("Elige al Usuario y su Nueva Sucursal");

        espacioUsuarioElegido.setLayout(new java.awt.GridLayout(1, 1));

        espacioSucursalElegida.setLayout(new java.awt.GridLayout(1, 1));

        espacioUsuarios.setLayout(new java.awt.GridLayout(0, 1));
        jScrollPane1.setViewportView(espacioUsuarios);

        espacioSucursales.setLayout(new java.awt.GridLayout(0, 1));
        jScrollPane2.setViewportView(espacioSucursales);

        jButton1.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        jButton1.setText("Cambiar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(41, 41, 41))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(espacioUsuarioElegido, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(espacioSucursalElegida, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(jButton1)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jButton2)
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(espacioUsuarioElegido, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(espacioSucursalElegida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(jButton1)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        menuSuperAdmin.setVisible(true);
        limpiarPaneles();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (usuario == null) {
            JOptionPane.showMessageDialog(this, "No se ha escogido al Usuario");
            return;
        }
        if (sucursal == null) {
            JOptionPane.showMessageDialog(this, "No se ha escogido una sucursal");
            return;
        }
        try {
            gestorUsuario.cambiarDeSucursal(sucursal.getIdSucursal(), usuario.getIdUsuario());
            JOptionPane.showMessageDialog(this, "Se ha cambiado a "+usuario.getNombre()+" a la sucursal "+sucursal.getNombre());
            quitarUsuarioElegido(plantilllaUsuario);
            quitarSucursalElegida();
        } catch (SQLException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());  
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel espacioSucursalElegida;
    private javax.swing.JPanel espacioSucursales;
    private javax.swing.JPanel espacioUsuarioElegido;
    private javax.swing.JPanel espacioUsuarios;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
    
    public void agregarUsuario(PlantillaUsuarioCambio plantilla) {
        espacioUsuarios.add(plantilla);
        actualizarUsuarios();
    }
    
    public void agregarUsuarioElegido(PlantillaUsuarioCambio plantilla) {
        espacioUsuarioElegido.add(plantilla);
        actualizarUsuarios();
        actualizarUsuarioElegido();
    } 
    
    public void quitarUsuarioElegido(PlantillaUsuarioCambio plantilla) {
        agregarUsuario(plantilla);
        actualizarUsuarioElegido();
        plantilllaUsuario = null;
        usuario = null;
    }
    
    public void agregarSucursal(PlantillaSucursalCambio plantilla) {
        espacioSucursales.add(plantilla);
        actualizarSucursales();
    }
    
    public void agregarSucursalElegida(PlantillaSucursalCambio plantilla) {
        espacioSucursalElegida.add(plantilla);
        actualizarSucursales();
        actualizarSucursalElegida();
    }
    
    public void quitarSucursalElegida() {
        agregarSucursal(plantillaSucursal);
        actualizarSucursalElegida();
        plantillaSucursal = null;
        sucursal = null;
    }
    
    private void actualizarUsuarios() {
        espacioUsuarios.revalidate();
        espacioUsuarios.repaint();
    }
    
    private void actualizarUsuarioElegido() {
        espacioUsuarioElegido.revalidate();
        espacioUsuarioElegido.repaint();
    }
    
    private void actualizarSucursales() {
        espacioSucursales.revalidate();
        espacioSucursales.repaint();
    }
    
    private void actualizarSucursalElegida() {
        espacioSucursalElegida.revalidate();
        espacioSucursalElegida.repaint();
    }
    
    private void limpiarPaneles() {
        espacioUsuarios.removeAll();
        actualizarUsuarios();
        espacioUsuarioElegido.removeAll();
        actualizarUsuarioElegido();
        espacioSucursales.removeAll();
        actualizarSucursales();
        espacioSucursalElegida.removeAll();
        actualizarSucursalElegida();
        plantilllaUsuario = null;
        usuario = null;
        plantillaSucursal = null;
        sucursal = null;
    }
    
}
