/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package OpcionesSuperAdmin.Frontent;

import Menus.VentanaMenuSuperAdmin;
import OpcionesAdministrador.Sucursal.ValidarFrontent;
import SQL.Sucursal.Sucursal;
import SQL.Usuario.GestorUsuario;
import com.mycompany.practica1_ipc2_ps.Roles;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author millin-115
 */
public class VentanaCrearUsuario extends javax.swing.JFrame {
    
    private final VentanaMenuSuperAdmin menuSuperAdmin;
    private final GestorUsuario gestorUsuario;
    private int rolElegido;
    private final Roles roles;
    private PlantillaSucursal plantilla;
    private Sucursal sucursal;
    
    public VentanaCrearUsuario(VentanaMenuSuperAdmin menuSuperAdmin, GestorUsuario gestorUsuario) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.menuSuperAdmin = menuSuperAdmin;
        this.gestorUsuario = gestorUsuario;
        this.roles = new Roles();
    }
    
    public void setSucursal(PlantillaSucursal plantilla, Sucursal sucursal) {
        this.plantilla = plantilla;
        this.sucursal = sucursal;
    }
    
    public Sucursal getSucursal() {
        return sucursal;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        espacioNombre = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        espacioContraseña = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        espacioRol = new javax.swing.JLabel();
        botonUsuario = new javax.swing.JButton();
        botonAdministrador = new javax.swing.JButton();
        botonSuperAdmin = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        espacioSucursalElegida = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        espacioSucursales = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        jLabel1.setText("Para crear un nuevo usuario llena los campos");

        espacioNombre.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N

        jButton1.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        jButton1.setText("Crear");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        jButton2.setText("Regresar");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        jLabel2.setText("Ingresa el nombre del Usuario");

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        jLabel3.setText("Ingresa la contraseña");

        espacioContraseña.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        jLabel4.setText("Escoge el rol que Tendra");

        espacioRol.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        espacioRol.setText("Ningun Rol");

        botonUsuario.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        botonUsuario.setText("Usuario");
        botonUsuario.addActionListener(this::botonUsuarioActionPerformed);

        botonAdministrador.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        botonAdministrador.setText("Administrador");
        botonAdministrador.addActionListener(this::botonAdministradorActionPerformed);

        botonSuperAdmin.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        botonSuperAdmin.setText("Super Administrador");
        botonSuperAdmin.addActionListener(this::botonSuperAdminActionPerformed);

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        jLabel5.setText("En que sucursal sera Asignado");

        espacioSucursalElegida.setLayout(new java.awt.GridLayout(1, 1));

        espacioSucursales.setLayout(new java.awt.GridLayout(0, 1));
        jScrollPane1.setViewportView(espacioSucursales);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(87, 87, 87)
                .addComponent(jButton2)
                .addGap(18, 18, 18))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(245, 245, 245)
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(303, 303, 303))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(283, 283, 283)
                                    .addComponent(jLabel3))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(194, 194, 194)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(espacioContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(espacioNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(117, 117, 117)
                                    .addComponent(botonUsuario)
                                    .addGap(74, 74, 74)
                                    .addComponent(botonAdministrador)
                                    .addGap(81, 81, 81)
                                    .addComponent(botonSuperAdmin))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(332, 332, 332)
                                    .addComponent(espacioRol))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(270, 270, 270)
                                    .addComponent(jLabel4)))
                            .addGap(16, 16, 16))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(69, 69, 69)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(espacioSucursalElegida, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(345, 345, 345)
                        .addComponent(jButton1)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(espacioNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(espacioContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonUsuario)
                    .addComponent(botonAdministrador)
                    .addComponent(botonSuperAdmin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(espacioRol)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(espacioSucursalElegida, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nombreUsuario = espacioNombre.getText();
        String contraseña = espacioContraseña.getText();
        if (ValidarFrontent.estaVacio(nombreUsuario) || ValidarFrontent.estaVacio(contraseña)) {
            JOptionPane.showMessageDialog(this, "No se puede dejar el espacio vacio");
            return;
        }
        if (!ValidarFrontent.revisionValido(nombreUsuario, 40)) {
            JOptionPane.showMessageDialog(this, "El nombre no puede sobrepasar los 50 caracteres");
            return;
        }
        if (!ValidarFrontent.revisionValido(contraseña, 15)) {
            JOptionPane.showMessageDialog(this, "La constraseña no puede tener mas de 20 caracteres");
            return;
        }
        if (rolElegido <= 0) {
            JOptionPane.showMessageDialog(this, "No se ha seleccionado un rol");
            return;
        }
        if (sucursal == null) {
            JOptionPane.showMessageDialog(this, "No se ha escogido una sucursal");
            return;
        }
        try {
            gestorUsuario.agregarUsuario(nombreUsuario, contraseña, rolElegido, sucursal.getIdSucursal());
            JOptionPane.showMessageDialog(this, "Se ha creado el Usuario "+nombreUsuario+" con exito");
            espacioNombre.setText("");
            espacioContraseña.setText("");
            escribirRol("Ningun Rol");
            rolElegido = 0;
            quitarEleccion();
        } catch (SQLException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        menuSuperAdmin.setVisible(true);
        limpiarSucursales();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void botonUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonUsuarioActionPerformed
        escribirRol("Usuario");
        rolElegido = roles.usuario;
    }//GEN-LAST:event_botonUsuarioActionPerformed

    private void botonAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAdministradorActionPerformed
        escribirRol("Administrador");
        rolElegido = roles.admin;
    }//GEN-LAST:event_botonAdministradorActionPerformed

    private void botonSuperAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSuperAdminActionPerformed
        escribirRol("Super Administrador");
        rolElegido = roles.superAdmin;
    }//GEN-LAST:event_botonSuperAdminActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAdministrador;
    private javax.swing.JButton botonSuperAdmin;
    private javax.swing.JButton botonUsuario;
    private javax.swing.JTextField espacioContraseña;
    private javax.swing.JTextField espacioNombre;
    private javax.swing.JLabel espacioRol;
    private javax.swing.JPanel espacioSucursalElegida;
    private javax.swing.JPanel espacioSucursales;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
    private void escribirRol(String rol) {
        espacioRol.setText(rol);
    }
    
    public void agregarSucursal(PlantillaSucursal plantilla) {
        espacioSucursales.add(plantilla);
        actualizarSucursales();
    }
    
    public void agregarSucursalElegida() {
        espacioSucursalElegida.add(plantilla);
        actualizarSucursales();
        actualizarElegida();
    }
    
    public void quitarEleccion() {
        agregarSucursal(plantilla);
        actualizarElegida();
        plantilla = null;
        sucursal = null;
    }
    
    private void actualizarElegida() {
        espacioSucursalElegida.revalidate();
        espacioSucursalElegida.repaint();
    }
    
    private void actualizarSucursales() {
        espacioSucursales.revalidate();
        espacioSucursales.repaint();
    }
    
    private void limpiarSucursales() {
        espacioSucursales.removeAll();
        actualizarSucursales();
        espacioSucursalElegida.removeAll();
        actualizarElegida();
        espacioNombre.setText("");
        espacioContraseña.setText("");
        escribirRol("Ningun Rol");
        rolElegido = 0;
        plantilla = null;
        sucursal = null;
    }
    
}
