/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package OpcionesSucursalProducto.Frontent;

/**
 *
 * @author millin-115
 */
public class PlantillaEstadistica extends javax.swing.JPanel {

    public PlantillaEstadistica(String campo1, String campo2, String campo3, String campo4) {
        initComponents();
        espacioNombre.setText(campo1);
        espacioSucursal.setText(campo2);
        espacioPuntuacion.setText(String.valueOf(campo3));
        espacioNivel.setText(String.valueOf(campo4));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        espacioNombre = new javax.swing.JLabel();
        espacioSucursal = new javax.swing.JLabel();
        espacioPuntuacion = new javax.swing.JLabel();
        espacioNivel = new javax.swing.JLabel();

        espacioNombre.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        espacioNombre.setText("Nombre");

        espacioSucursal.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        espacioSucursal.setText("Sucursal");

        espacioPuntuacion.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        espacioPuntuacion.setText("Puntuacion");

        espacioNivel.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        espacioNivel.setText("Nivel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(espacioNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(espacioSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(espacioPuntuacion, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(espacioNivel, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(espacioNombre)
                    .addComponent(espacioSucursal)
                    .addComponent(espacioPuntuacion)
                    .addComponent(espacioNivel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel espacioNivel;
    private javax.swing.JLabel espacioNombre;
    private javax.swing.JLabel espacioPuntuacion;
    private javax.swing.JLabel espacioSucursal;
    // End of variables declaration//GEN-END:variables
    
}
