/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package OpcionesSucursalProducto.Frontent;

import Excepciones.DeshabilitarException;
import Excepciones.ListaException;
import OpcionesSucursalProducto.OpcionDesactivarActivar;
import OpcionesSucursalProducto.OpcionRenombrarProducto;
import SQL.Productos.Producto;
import Usuario.Usuario;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author millin-115
 */
public class PlantillaProducto extends javax.swing.JPanel {
    
    private final OpcionDesactivarActivar opcionesBoton;
    private final OpcionRenombrarProducto opcionRenombrarProducto;
    private final Producto producto;
    private final Usuario usuario;
    private boolean habilitadoEnSucursal;
    private boolean opcionRenombrar;
    
    public PlantillaProducto(OpcionDesactivarActivar opciones, OpcionRenombrarProducto opcionRenombrarProducto, Producto producto, Usuario usuario) {
        initComponents();
        this.opcionesBoton = opciones;
        this.opcionRenombrarProducto = opcionRenombrarProducto;
        this.producto = producto;
        this.usuario = usuario;
        this.opcionRenombrar = true;
        setNombre(producto.getNombre());
        mostrarEspacioRenombrar();
    }
    
    public void setNombre(String nombreProducto) {
        espacioNombre.setText(nombreProducto);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        espacioNombre = new javax.swing.JLabel();
        botonActivarDesactivar = new javax.swing.JButton();
        botonRenombrar = new javax.swing.JButton();
        espacioRenombrar = new javax.swing.JPanel();
        espacioNuevoNombre = new javax.swing.JTextField();
        botonCambiarNombre = new javax.swing.JButton();

        espacioNombre.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        espacioNombre.setText("Nombre");

        botonActivarDesactivar.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        botonActivarDesactivar.setText("Activar Producto");
        botonActivarDesactivar.addActionListener(this::botonActivarDesactivarActionPerformed);

        botonRenombrar.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        botonRenombrar.setText("Renombrar");
        botonRenombrar.addActionListener(this::botonRenombrarActionPerformed);

        espacioNuevoNombre.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N

        botonCambiarNombre.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        botonCambiarNombre.setText("Cambiar Nombre");
        botonCambiarNombre.addActionListener(this::botonCambiarNombreActionPerformed);

        javax.swing.GroupLayout espacioRenombrarLayout = new javax.swing.GroupLayout(espacioRenombrar);
        espacioRenombrar.setLayout(espacioRenombrarLayout);
        espacioRenombrarLayout.setHorizontalGroup(
            espacioRenombrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(espacioRenombrarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(espacioRenombrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(espacioNuevoNombre)
                    .addGroup(espacioRenombrarLayout.createSequentialGroup()
                        .addComponent(botonCambiarNombre)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        espacioRenombrarLayout.setVerticalGroup(
            espacioRenombrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(espacioRenombrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(espacioNuevoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonCambiarNombre)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(espacioNombre)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botonActivarDesactivar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonRenombrar)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(espacioRenombrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(espacioNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonActivarDesactivar)
                    .addComponent(botonRenombrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(espacioRenombrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonActivarDesactivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActivarDesactivarActionPerformed
        try {
            opcionesBoton.habilitarDeshabilitar(habilitadoEnSucursal, producto, this, usuario);
        } catch (ListaException | SQLException | ClassNotFoundException | DeshabilitarException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_botonActivarDesactivarActionPerformed

    private void botonRenombrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRenombrarActionPerformed
        mostrarEspacioRenombrar();
    }//GEN-LAST:event_botonRenombrarActionPerformed

    private void botonCambiarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCambiarNombreActionPerformed
        if (opcionRenombrarProducto.estaVacio(espacioNuevoNombre.getText())) {
            JOptionPane.showMessageDialog(null, "No se puede dejar vacio el espacio del Nombre");
            return;
        }
        if (espacioNuevoNombre.getText().length() > 50) {
            JOptionPane.showMessageDialog(null, "El nombre no puede superar lo 50 caracteres");
            return;
        }
        try {
            opcionRenombrarProducto.renombrar(producto, espacioNuevoNombre.getText(), this);
            mostrarEspacioRenombrar();
            espacioNuevoNombre.setText("");
        } catch (SQLException | ClassNotFoundException | ListaException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_botonCambiarNombreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActivarDesactivar;
    private javax.swing.JButton botonCambiarNombre;
    private javax.swing.JButton botonRenombrar;
    private javax.swing.JLabel espacioNombre;
    private javax.swing.JTextField espacioNuevoNombre;
    private javax.swing.JPanel espacioRenombrar;
    // End of variables declaration//GEN-END:variables
    
    
    public void setHabilitado(boolean habilitado) {
        this.habilitadoEnSucursal = habilitado;
    }
    
    public void setTextoBoton(String texto) {
        botonActivarDesactivar.setText(texto);
    }

    public void mostrarEspacioRenombrar() {
        opcionRenombrar = !opcionRenombrar;
        espacioRenombrar.setVisible(opcionRenombrar);
    }
    
    
    
}
