/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package OpcionesSucursalProducto.Frontent;

import Archivos.GuardadoArchivos;
import Archivos.GuardadoRanking;
import Excepciones.ListaException;
import java.io.IOException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author millin-115
 */
public class VentanaRanking extends javax.swing.JFrame {
    
    private JFrame ventanaAnterior;
    private GuardadoArchivos guardadoArchivos;
    
    public VentanaRanking() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public void setTituloEstadisticas(String titulo) {
        espacioTitulo.setText(titulo);
    }
    
    public void setVentanaAnterior(JFrame ventanaAnterior) {
        this.ventanaAnterior = ventanaAnterior;
    }

    public void setGuardadoRanking(GuardadoArchivos guardadoArchivos) {
        this.guardadoArchivos = guardadoArchivos;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonRegresar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        espacioRanking = new javax.swing.JPanel();
        espacioTitulo = new javax.swing.JLabel();
        texto1 = new javax.swing.JLabel();
        texto2 = new javax.swing.JLabel();
        texto3 = new javax.swing.JLabel();
        texto4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonRegresar.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        botonRegresar.setText("Regresar");
        botonRegresar.addActionListener(this::botonRegresarActionPerformed);

        espacioRanking.setLayout(new java.awt.GridLayout(0, 1));
        jScrollPane1.setViewportView(espacioRanking);

        espacioTitulo.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        espacioTitulo.setText("Estadisticas de la Sucursal Nombre");

        texto1.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        texto1.setText("Nombre");

        texto2.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        texto2.setText("Sucursal");

        texto3.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        texto3.setText("Puntuacion");

        texto4.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        texto4.setText("Nivel");

        jButton1.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        jButton1.setText("Exportar a CSV");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonRegresar)
                .addGap(30, 30, 30))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(texto1)
                                .addGap(222, 222, 222)
                                .addComponent(texto2)
                                .addGap(133, 133, 133)
                                .addComponent(texto3)
                                .addGap(92, 92, 92)
                                .addComponent(texto4))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 881, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(335, 335, 335)
                        .addComponent(espacioTitulo)))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonRegresar)
                    .addComponent(jButton1))
                .addGap(12, 12, 12)
                .addComponent(espacioTitulo)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(texto1)
                    .addComponent(texto2)
                    .addComponent(texto3)
                    .addComponent(texto4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
        this.setVisible(false);
        limpiarVentana();
        ventanaAnterior.setVisible(true);
    }//GEN-LAST:event_botonRegresarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            guardadoArchivos.guardarArchivos();
            JOptionPane.showMessageDialog(this, "Se exportaron los datos con exito");
        } catch (ListaException | IOException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonRegresar;
    private javax.swing.JPanel espacioRanking;
    private javax.swing.JLabel espacioTitulo;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel texto1;
    private javax.swing.JLabel texto2;
    private javax.swing.JLabel texto3;
    private javax.swing.JLabel texto4;
    // End of variables declaration//GEN-END:variables
    
    public void setTextos(String texto1, String texto2, String texto3, String texto4) {
        this.texto1.setText(texto1);
        this.texto2.setText(texto2);
        this.texto3.setText(texto3);
        this.texto4.setText(texto4);
    }
    
    public void agregarEstadistica(JPanel plantilla) {
        espacioRanking.add(plantilla);
        espacioRanking.revalidate();
        espacioRanking.repaint();
    }
    
    public void limpiarVentana() {
        espacioRanking.removeAll();
        espacioRanking.revalidate();
        espacioRanking.repaint();
    }
    
}
